'use client'

import { useState } from 'react'
import { ArrowRight, BatteryCharging, Car, Check, ChevronDown, CircleParking, Droplets, Gauge, Heart, Menu, Search, ShieldCheck, Sparkles, Star, Wrench, X } from 'lucide-react'

const cars = [
  { name: 'Mercedes-Benz GLC 300', meta: '2024 · 12,400 km · Automatic', price: 'AED 279,000', image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=85', tag: 'Verified', location: 'Dubai' },
  { name: 'Porsche Cayenne S', meta: '2023 · 18,200 km · Automatic', price: 'AED 365,000', image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=85', tag: 'Featured', location: 'Abu Dhabi' },
  { name: 'BMW 7 Series', meta: '2024 · 8,900 km · Automatic', price: 'AED 429,000', image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=85', tag: 'New arrival', location: 'Dubai' },
]

const services = [
  ['Buy a car', 'Find your next drive', Car], ['Rent a car', 'Freedom by the day', CircleParking], ['Wash & detail', 'Look after your car', Droplets], ['Maintenance', 'Keep moving forward', Wrench], ['Roadside help', 'We are here 24/7', BatteryCharging], ['Inspection', 'Buy with confidence', ShieldCheck],
]

export default function Page() {
  const [activeTab, setActiveTab] = useState('Buy')
  const [arabic, setArabic] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [favorites, setFavorites] = useState<number[]>([])
  const copy = arabic ? { nav: ['الرئيسية', 'شراء السيارات', 'تأجير السيارات', 'الخدمات'], hero: 'كل ما تحتاجه سيارتك، في مكان واحد.', sub: 'اشترِ، استأجر، صِن، واعتنِ بسيارتك عبر منصة واحدة سلسة.', search: 'ابحث عن سيارتك القادمة', featured: 'مختارات مميزة', explore: 'اكتشف المزيد' } : { nav: ['Home', 'Buy cars', 'Rent cars', 'Services'], hero: 'Everything your car needs, in one place.', sub: 'Buy, rent, maintain, and care for your car through one seamless automotive platform.', search: 'Find your next car', featured: 'Curated for your journey', explore: 'Explore all cars' }
  return (
    <main dir={arabic ? 'rtl' : 'ltr'} className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-50 border-b border-border/70 bg-background/90 backdrop-blur-xl">
        <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10">
          <a href="/" className="flex items-center gap-3" aria-label="Motory home"><span className="flex h-9 w-9 items-center justify-center bg-primary text-primary-foreground"><span className="text-lg font-bold">M</span></span><span className="text-xl font-bold tracking-tight">motory<span className="text-accent">.</span></span></a>
          <nav className="hidden items-center gap-7 text-sm font-medium text-muted-foreground lg:flex">{copy.nav.map((item) => <a key={item} href="#" className="transition-colors hover:text-foreground">{item}</a>)}<a href="#services">Car care</a></nav>
          <div className="flex items-center gap-2"><button className="hidden h-10 items-center gap-2 border border-border px-3 text-sm font-medium sm:flex"><Search size={16} /> Search</button><button onClick={() => setArabic(!arabic)} className="h-10 border border-border px-3 text-xs font-bold tracking-wide">{arabic ? 'EN' : 'عربي'}</button><button className="hidden h-10 bg-primary px-4 text-sm font-semibold text-primary-foreground sm:block">List your car</button><button aria-label="Open menu" onClick={() => setMobileOpen(!mobileOpen)} className="p-2 lg:hidden">{mobileOpen ? <X /> : <Menu />}</button></div>
        </div>
        {mobileOpen && <nav className="border-t border-border bg-background px-5 py-5 lg:hidden">{copy.nav.map((item) => <a key={item} href="#" className="block border-b border-border py-4 text-sm font-semibold">{item}</a>)}<a href="#services" className="block py-4 text-sm font-semibold">Car care</a></nav>}
      </header>

      <section className="relative min-h-[650px] overflow-hidden bg-primary text-primary-foreground"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,14,24,.98)_0%,rgba(8,14,24,.78)_42%,rgba(8,14,24,.12)_100%),url('https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=2200&q=85')] bg-cover bg-center" /><div className="relative mx-auto flex max-w-[1440px] flex-col justify-center px-5 py-24 lg:min-h-[650px] lg:px-10"><div className="max-w-2xl"><div className="mb-7 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.2em] text-accent"><span className="h-px w-9 bg-accent" /> The automotive ecosystem</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.04] tracking-[-.04em] text-balance sm:text-7xl">{copy.hero}</h1><p className="mt-7 max-w-lg text-lg leading-8 text-primary-foreground/70">{copy.sub}</p></div><div className="mt-12 max-w-3xl border border-primary-foreground/20 bg-primary/80 p-2 backdrop-blur-md"><div className="flex gap-1 border-b border-primary-foreground/15 px-2">{['Buy', 'Rent', 'Services'].map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={`px-5 py-4 text-sm font-semibold ${activeTab === tab ? 'border-b-2 border-accent text-primary-foreground' : 'text-primary-foreground/55'}`}>{tab}</button>)}</div><div className="grid gap-2 p-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><label className="flex flex-col gap-2 bg-primary-foreground/10 px-4 py-3 text-xs text-primary-foreground/55">{activeTab === 'Buy' ? 'Make & model' : activeTab === 'Rent' ? 'Pickup location' : 'Service type'}<span className="flex items-center justify-between text-sm font-medium text-primary-foreground">{activeTab === 'Buy' ? 'All vehicles' : activeTab === 'Rent' ? 'Dubai, UAE' : 'All services'}<ChevronDown size={15} /></span></label><label className="flex flex-col gap-2 bg-primary-foreground/10 px-4 py-3 text-xs text-primary-foreground/55">{activeTab === 'Rent' ? 'Pickup date' : 'Budget'}<span className="flex items-center justify-between text-sm font-medium text-primary-foreground">{activeTab === 'Rent' ? 'Select date' : 'Any price'}<ChevronDown size={15} /></span></label><label className="hidden flex-col gap-2 bg-primary-foreground/10 px-4 py-3 text-xs text-primary-foreground/55 sm:flex">Location<span className="flex items-center justify-between text-sm font-medium text-primary-foreground">All locations <ChevronDown size={15} /></span></label><button className="flex items-center justify-center gap-2 bg-accent px-5 py-3 text-sm font-bold text-accent-foreground transition-transform hover:scale-[1.02]"><Search size={17} />{activeTab === 'Services' ? 'Explore' : 'Search'}</button></div></div></div></section>

      <section id="services" className="mx-auto max-w-[1440px] px-5 py-20 lg:px-10"><div className="mb-9 flex items-end justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-accent">One platform. Every need.</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{arabic ? 'خدمات مصممة لرحلتك' : 'Built around your journey'}</h2></div><a href="#" className="hidden items-center gap-2 text-sm font-semibold sm:flex">{copy.explore}<ArrowRight size={16} /></a></div><div className="grid grid-cols-2 border-l border-t border-border sm:grid-cols-3 lg:grid-cols-6">{services.map(([title, desc, Icon]) => <a href="#" key={title as string} className="group border-b border-r border-border p-5 transition-colors hover:bg-secondary sm:p-6"><Icon className="mb-10 text-accent transition-transform group-hover:-translate-y-1" size={24} strokeWidth={1.5} /><h3 className="font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc as string}</p></a>)}</div></section>

      <section className="bg-secondary/60 py-20"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-accent">Handpicked inventory</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{copy.featured}</h2></div><a href="/cars" className="hidden items-center gap-2 text-sm font-semibold sm:flex">{copy.explore}<ArrowRight size={16} /></a></div><div className="grid gap-5 md:grid-cols-3">{cars.map((car, i) => <article key={car.name} className="group overflow-hidden border border-border bg-background"><div className="relative aspect-[1.3] overflow-hidden"><img src={car.image} alt={car.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-4 top-4 bg-accent px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-accent-foreground">{car.tag}</span><button aria-label={`Save ${car.name}`} onClick={() => setFavorites((f) => f.includes(i) ? f.filter(x => x !== i) : [...f, i])} className="absolute right-4 top-4 flex h-9 w-9 items-center justify-center bg-background/90"><Heart size={16} fill={favorites.includes(i) ? 'currentColor' : 'none'} /></button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{car.name}</h3><p className="mt-2 text-sm text-muted-foreground">{car.meta}</p></div><ShieldCheck className="shrink-0 text-accent" size={18} /></div><div className="mt-6 flex items-end justify-between border-t border-border pt-4"><div><p className="text-xs text-muted-foreground">Starting from</p><p className="mt-1 text-lg font-bold">{car.price}</p></div><p className="text-xs text-muted-foreground">{car.location}</p></div></div></article>)}</div></div></section>

      <section className="mx-auto grid max-w-[1440px] gap-5 px-5 py-20 lg:grid-cols-2 lg:px-10"><div className="relative min-h-[400px] overflow-hidden bg-primary p-8 text-primary-foreground sm:p-12"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,14,24,.95),rgba(8,14,24,.25)),url('https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1200&q=85')] bg-cover bg-center" /><div className="relative flex h-full flex-col justify-between"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-accent">Sell with confidence</p><h2 className="max-w-sm text-3xl font-bold tracking-tight sm:text-4xl">Your car deserves a better market.</h2><p className="mt-5 max-w-sm leading-7 text-primary-foreground/65">Reach serious buyers, get a fair valuation, and sell on your terms.</p></div><a href="/sell" className="mt-12 flex w-fit items-center gap-2 bg-accent px-5 py-3 text-sm font-bold text-accent-foreground">Get a free valuation <ArrowRight size={16} /></a></div></div><div className="flex min-h-[400px] flex-col justify-between bg-accent p-8 text-accent-foreground sm:p-12"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em]">Always on your side</p><h2 className="max-w-sm text-3xl font-bold tracking-tight sm:text-4xl">Help is closer than you think.</h2><p className="mt-5 max-w-sm leading-7 text-accent-foreground/75">Roadside assistance, from a flat tire to a full tow. One tap and we are on our way.</p></div><div className="mt-12 flex items-center justify-between border-t border-accent-foreground/20 pt-5"><div><p className="text-4xl font-bold">24/7</p><p className="mt-1 text-sm">Support when it matters</p></div><ArrowRight size={28} /></div></div></section>

      <section className="border-t border-border bg-primary py-20 text-primary-foreground"><div className="mx-auto flex max-w-[1440px] flex-col items-start justify-between gap-8 px-5 sm:flex-row sm:items-end lg:px-10"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-accent">Drive forward</p><h2 className="max-w-xl text-4xl font-bold tracking-tight sm:text-5xl">A smarter way to move through life.</h2></div><a href="/cars" className="flex items-center gap-2 bg-accent px-6 py-4 text-sm font-bold text-accent-foreground">Start exploring <ArrowRight size={17} /></a></div></section>
      <footer className="bg-primary px-5 pb-8 text-primary-foreground lg:px-10"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-6 border-t border-primary-foreground/15 pt-7 text-xs text-primary-foreground/50 sm:flex-row"><p>© 2026 motory. The automotive ecosystem.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Contact</a></div></div></footer>
    </main>
  )
}
