import { Filter, Heart, Map, Search, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { PageHero } from '@/components/page-hero'

const cars = [
  ['mercedes-glc-300','Mercedes-Benz GLC 300','279,000','1618843479313-40f8afb4b4d8'],
  ['porsche-cayenne-s','Porsche Cayenne S','365,000','1503376780353-7e6692767b70'],
  ['bmw-7-series','BMW 7 Series','429,000','1555215695-3004980ad54e'],
  ['audi-rs-q8','Audi RS Q8','389,000','1606664515524-ed2f786a0cdb'],
  ['range-rover-sport','Range Rover Sport','499,000','1606664515524-ed2f786a0cdb'],
  ['mercedes-c-class','Mercedes-Benz C-Class','219,000','1492144534655-ae79c964c9d7'],
]

export default function CarsPage() {
  return <main className="min-h-screen bg-background"><SiteHeader/><PageHero eyebrow="Marketplace" title="Find a car that feels like you." description="Verified inventory, transparent details, intelligent filters and premium discovery — all designed to make choosing your next car feel effortless." image="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=2200&q=88"><div className="flex max-w-2xl gap-2 border border-white/15 bg-white/5 p-2 backdrop-blur"><div className="flex flex-1 items-center gap-3 px-4"><Search size={17} className="text-accent"/><span className="text-sm text-white/55">Search make, model or keyword</span></div><button className="bg-accent px-6 py-4 text-xs font-black text-accent-foreground">Search</button></div></PageHero>
  <section className="mx-auto max-w-[1480px] px-5 py-14 lg:px-10"><div className="grid gap-8 lg:grid-cols-[270px_1fr]"><aside className="hidden lg:block"><div className="sticky top-24 border border-border bg-card p-6"><div className="flex items-center justify-between"><h2 className="font-black">Refine search</h2><button className="text-xs font-bold text-accent">Reset</button></div>{['Condition','Make & model','Price range','Year','Body type','Transmission','Fuel type','Location'].map(x=><div className="border-b border-border py-5" key={x}><p className="text-sm font-bold">{x}</p><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground">Any <SlidersHorizontal size={14}/></div></div>)}</div></aside><div><div className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-center"><div><p className="text-sm font-bold">248 vehicles</p><p className="mt-1 text-xs text-muted-foreground">Updated a few minutes ago</p></div><div className="flex gap-2"><button className="flex items-center gap-2 border border-border px-4 py-2.5 text-xs font-bold lg:hidden"><Filter size={15}/> Filters</button><button className="flex items-center gap-2 border border-border px-4 py-2.5 text-xs font-bold"><Map size={15}/> Map</button><button className="border border-border px-4 py-2.5 text-xs font-bold">Newest first</button></div></div><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cars.map(([slug,name,price,img])=><article key={slug} className="group overflow-hidden border border-border bg-card"><a href={`/cars/${slug}`} className="relative block aspect-[1.28] overflow-hidden"><img className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" src={`https://images.unsplash.com/photo-${img}?auto=format&fit=crop&w=1000&q=84`} alt={name}/><span className="absolute left-4 top-4 bg-[#0b1017] px-2.5 py-1 text-[9px] font-black uppercase tracking-[.14em] text-white">Verified</span><span className="absolute right-4 top-4 grid h-9 w-9 place-items-center bg-white/90"><Heart size={16}/></span></a><div className="p-5"><div className="flex justify-between gap-3"><div><h2 className="font-black tracking-[-.02em]">{name}</h2><p className="mt-2 text-xs text-muted-foreground">2024 · Automatic · 12,400 km</p></div><ShieldCheck className="shrink-0 text-accent" size={18}/></div><div className="mt-5 flex items-end justify-between border-t border-border pt-4"><div><p className="text-[9px] uppercase tracking-[.13em] text-muted-foreground">From</p><b className="text-lg">AED {price}</b></div><a className="text-xs font-black text-accent" href={`/cars/${slug}`}>View details</a></div></div></article>)}</div></div></div></section><SiteFooter/></main>
}
